### ISSUE TITLE
Change the parser from 'pandoc' to 'md4c'

### ISSUE THREAD

**Issue by mondeja** [mondeja/md2po#13]
## Pros

- [x] It's much faster.
- [x] Reimplements the program to fit CommonMark spec.
- [x] It's easier to maintain.
- [x] Installation does not require previous Pandoc downloads in Linux.
- [x] Take advantage of this branch to remove custom markup characters support (not useful and painfull maintainability).

## Contras

- [x] Definition lists are not supported by CommonMark (I don't want them anyway).
- [x] Installation is not direct in Mac and Windows (`md4c` must be compiled), but the truth is that I do not care, almost all Python package downloads occur in Linux environments. 
- [ ] I'm getting segment violations with indented code blocks, even are supported by CommonMark (I don't want them anyway). I need to investigate this more deeply and report it in md4c python bindings repo, but maybe is better to wait until a more stable release comes out.

## TODO

- [ ] Change `format` parameter by md4c `flags`.
